### ISSUE TITLE
Display of multiple lines of a test case result needed

### ISSUE THREAD

**Issue by doyleLai** [bytebang/vpl-junit#1]
It is a great project that help teachers a lot!! 
However, due to unknown reason, the Comments tab in the Edit page or the assessment report can only display the first line of the result of each test case. Student role is unable to view the Execution tab in the Edit page. Therefore, if a test case failed and the value contains multiple lines, students will not be able to see the expected and the actual value.

In the picture, you can see the first test case failed. The report ends at \n character and the rest of the contents are not displayed.
![Untitled](https://user-images.githubusercontent.com/5112828/75624638-2db05c00-5bf1-11ea-8083-5abbf4526d5e.png)
.

It would be great if this can be fixed.

**Comment by bytebang** [comment]
I can reproduce this behavior. The full result (with all lines) can always be seen  in the description pane (below the comments).

The reason why this was implemented is, that the comments are not flooded with information. (Usually the first line of a stacktrace gives a meaningful hint).

Am I missing something, or do you have another usecase where you need this feature ?

**Comment by doyleLai** [comment]
Oh, I guess the behaviour differed in different Moodle.
Because the description pane in my Moodle always displays the description of the activity. If the description is empty, the pane just doesn't appear. 
![Untitled](https://user-images.githubusercontent.com/5112828/75628073-88a57b80-5c10-11ea-9679-cac6772e25c4.png)
![Untitled2](https://user-images.githubusercontent.com/5112828/75628074-8b07d580-5c10-11ea-85fd-5ba837418933.png)

I guess some settings are overriding the content of description pane?

**Comment by doyleLai** [comment]
Just realised the feature is added.
Thanks!
